# cloudflared     akina-underpass
# jellyfin        100.99.0.0:8096       jf
# plex            (only for tv)
# qbittorrent     qbt
# vaultwarden     vw
# glances         g

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - services
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/akina/configs/jellyfin:/config
      - /home/akina/data/media:/media
    ports:
      - 8096:8096
    networks:
      - services
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VERSION=docker
    volumes:
      - /home/akina/configs/plex:/config
      - /home/akina/data/media:/media
    network_mode: host
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - TZ=Asia/Kolkata
      - SIGNUPS_ALLOWED=false
      - WEBSOCKET_ENABLED=true
    volumes:
      - /home/akina/data/vaultwarden:/data
    networks:
      - services
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /home/akina/configs/qbittorrent:/config
      - /home/akina/data/media:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - services
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    network_mode: host
    restart: unless-stopped

networks:
  services:
    external: true
