services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
       - /home/user/configs/cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/user/configs/jellyfin:/config
      - /home/user/data/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - TZ=Asia/Kolkata
      - SIGNUPS_ALLOWED=false
      - WEBSOCKET_ENABLED=true
    volumes:
      - /home/user/data/vaultwarden:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/user/configs/qbittorrent:/config
      - /home/user/data/media:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  axew:
    image: adithyasrc/axew:latest
    container_name: axew
    pid: host
    privileged: true
    volumes:
      - /home/user/configs/axew/config.yaml:/app/config.yaml:ro
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-gotenberg
      - paperless-tika
    ports:
      - "8000:8000"
    volumes:
      - /home/user/data/paperless/data:/usr/src/paperless/data
      - /home/user/data/paperless/media:/usr/src/paperless/media
      - /home/user/data/paperless/export:/usr/src/paperless/export
      - /home/user/data/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-db:6379
      PAPERLESS_DBENGINE: sqlite
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${PAPERLESS_CSRF_TRUSTED_ORIGINS}

  paperless-db:
    image: docker.io/valkey/valkey:9-alpine
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - /home/user/data/paperless/valkey:/data

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.34
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless-tika:
    image: docker.io/apache/tika:3.3.1.0
    container_name: paperless-tika
    restart: unless-stopped

#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Asia/Kolkata
#      - VERSION=docker
#    volumes:
#      - /home/user/configs/plex:/config
#      - /home/user/data/media:/media
#    network_mode: host
#    restart: unless-stopped
