ingress:
  - hostname: qb.1003211.xyz
    service: http://qbittorrent:8080

  - hostname: vw.1003211.xyz
    service: http://vaultwarden:80

  - hostname: ax.1003211.xyz
    service: http://axew:8080

  - hostname: pl.1003211.xyz
    service: http://paperless:8000

  - hostname: nd.1003211.xyz
    service: http://navidrome:4533

  - hostname: ss.1003211.xyz
    service: http://soulseek:5030

  - service: http_status:404
